#!/bin/bash
set -ex

ESMINI_INSTALL_PREFIX=${ESMINI_INSTALL_PREFIX:-/usr/local}

ESMINI_OSG_SOURCE_DIR="/tmp/osg"
ESMINI_OSG_BUILD_DIR=${ESMINI_OSG_SOURCE_DIR}/build
ESMINI_OSG_GIT_URL="https://github.com/OpenSceneGraph/OpenSceneGraph"
ESMINI_OSG_VERSION=${ESMINI_OSG_VERSION:-3.6.5}
ESMINI_OSG_BUILD_SHARED_LIBS=${ESMINI_OSG_BUILD_SHARED_LIBS:-OFF}
ESMINI_OSG_BUILD_APPLICATIONS=${ESMINI_OSG_BUILD_APPLICATIONS:-OFF}

if [ ! -d "${ESMINI_OSG_SOURCE_DIR}" ]; then
  git clone "${ESMINI_OSG_GIT_URL}" ${ESMINI_OSG_SOURCE_DIR} \
    --depth 1 \
    --branch "OpenSceneGraph-${ESMINI_OSG_VERSION}" \
    --recurse-submodules
fi

cmake \
  -S ${ESMINI_OSG_SOURCE_DIR} \
  -B ${ESMINI_OSG_BUILD_DIR} \
  -DOPENGL_PROFILE=GL2 \
  -DOSG_AGGRESSIVE_WARNINGS=OFF \
  -DDYNAMIC_OPENSCENEGRAPH="${ESMINI_OSG_BUILD_SHARED_LIBS}" \
  -DDYNAMIC_OPENTHREADS="${ESMINI_OSG_BUILD_SHARED_LIBS}" \
  -DBUILD_OSG_APPLICATIONS="${ESMINI_OSG_BUILD_APPLICATIONS}" \
  -DBUILD_OSG_EXAMPLES=OFF \
  -DBUILD_OSG_DEPRECATED_SERIALIZERS=OFF \
  -DBUILD_DOCUMENTATION=OFF \
  -DBUILD_OSG_PLUGINS=ON \
  -DCMAKE_INSTALL_PREFIX="${ESMINI_INSTALL_PREFIX}" \
  -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON
cmake --build ${ESMINI_OSG_BUILD_DIR} --target install

# Cleanup
rm -rf ${ESMINI_OSG_SOURCE_DIR} ${ESMINI_OSG_BUILD_DIR}
